# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - api-fractus-v1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_ad51dc0e97cb4dafbb85c9e6305d65a5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5887c49b4b16420d9afd95e87ab11f40 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_ad51dc0e97cb4dafbb85c9e6305d65a5 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'api-fractus-v1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_45250aa1f6cf4ca9a66531fe8180d0fe }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_ad51dc0e97cb4dafbb85c9e6305d65a5 }}/appsvc/staticsite:${{ github.sha }}'